"""Data files of the home page (docs/index.html), exported from a CaMa-Flood-GPU run.

    python tools/home_data.py --params .../inp/glb_15min/parameters.nc \
        --run .../out/glb_15min_e2o --runoff .../e2o_ecmwf_wrr2_glob15_day_Runoff_2000.nc \
        --hires .../map/glb_15min/1min --forcing "daily eartH2Observe WRR2 runoff (ECMWF HTESSEL, 0.25°)" \
        --spin-up-years 1

The run directory must hold one year of daily `total_outflow_mean` and `river_depth_mean`
and the monthly `total_outflow_max_mean` for all catchments (`*_rank*.nc`); --runoff is
the forcing file of that year and --hires the 1-arcmin maps of the CaMa-Flood map
(`1min.catmxy.bin`, `1min.uparea.bin`, `1min.downxy.bin`). Writes two small scripts to
docs/home/data/:

    rivers.js      the river network as reaches with daily mean discharge (hero map), the
                   GPU of each basin (multi-GPU figure), the daily discharge at all river
                   mouths (hero sparkline), the main stems of well-known rivers and the
                   annual mean runoff of the forcing on a coarse grid (runoff figure)
    hydrograph.js  daily mean outflow and river depth, monthly maximum outflow and the
                   channel and floodplain parameters at gauges on some of those rivers,
                   and the unit catchments and rivers around the last gauge on the
                   1-arcmin map with the daily discharge of each between its own low and
                   high water of the year (storage figure)

The network keeps catchments with an upstream area of at least --min-upstream-km2. A
reach is a chain of catchments with one upstream catchment each and one upstream-area
class; it is stored as a polyline of outlet positions (0.05 degree steps) and carries
the daily mean discharge at its downstream end on a log scale in 4 bits, packed as runs
(see pack_levels); reaches of the larger rivers also carry it in 32 steps between their
own lowest and highest daily discharge, which the hero map reads out under the pointer.
Basins go to GPUs largest first, each to the least loaded GPU, as CaMa-Flood-GPU reports
its loads. A main stem is traced from the largest catchment near
the given mouth up through the upstream catchment with the largest area.
"""

from __future__ import annotations

import argparse
import base64
import glob
import json
import re
import struct
from pathlib import Path

import netCDF4
import numpy as np

DATA = Path(__file__).resolve().parents[1] / "docs" / "home" / "data"
LEVEL_KM2 = (1e3, 2e4, 1e5, 5e5, 2e6)  # upstream-area classes: line weight
PER_DEG = 20  # polyline positions in 0.05 degree units
DECADES = 6  # discharge range of the colour scale
LEVELS = 15  # 4-bit discharge levels 0..15
FINE_LEVEL = 3  # reaches of this upstream-area class and up also get FINE_STEPS steps
FINE_STEPS = 31  # between each such reach's own lowest and highest daily discharge
# name, longitude and latitude near the mouth
MAIN_STEMS = (
    ("Lena", 127.6, 72.4),
    ("Amazon", -50.7, -0.4),
    ("Congo", 12.4, -6.0),
    ("Nile", 31.0, 31.4),
    ("Mississippi", -89.3, 29.2),
    ("Paraná", -58.4, -34.0),
    ("Niger", 6.0, 4.6),
    ("Ob", 69.0, 66.6),
    ("Yenisei", 83.5, 70.5),
    ("Amur", 140.7, 52.9),
    ("Yangtze", 121.5, 31.4),
    ("Ganges", 90.5, 22.6),
    ("Mekong", 106.6, 9.9),
    ("Mackenzie", -134.9, 68.5),
    ("Yukon", -164.5, 62.6),
    ("Volga", 47.8, 46.2),
    ("Danube", 29.6, 45.2),
    ("Murray", 139.0, -35.5),
)
# river, gauge, longitude, latitude: the catchments of hydrograph.js, on those main stems
STATIONS = (("Mekong", "Mukdahan", 104.74, 16.54), ("Amazon", "Manacapuru", -60.6, -3.3))
RUNOFF_DEG = 2  # cell size of the runoff map
RUNOFF_MAX = 6.0  # mm/day at the top of its square-root colour scale
HIRES = 60  # cells per degree of the 1-arcmin map
PLAN_HALF = (1.2, 0.5)  # half width and height in degrees of the plan view
RIVER_KM2 = (2e3, 2e4, 2e5)  # upstream-area classes of the plan view's rivers


def write_js(name: str, payload: dict) -> None:
    DATA.mkdir(parents=True, exist_ok=True)
    path = DATA / f"{name}.js"
    path.write_text(
        "/* generated by tools/home_data.py; do not edit */\n"
        "window.HOME = window.HOME || {};\n"
        f"window.HOME.{name} = {json.dumps(payload, ensure_ascii=False, separators=(',', ':'))};\n",
        encoding="utf-8",
    )
    print(f"wrote {path} ({path.stat().st_size / 1024:.0f} KiB)")


def b64(data: bytes) -> str:
    return base64.b64encode(data).decode("ascii")


def polyline(xy: np.ndarray, meta: int = 0) -> bytes:
    """uint16 x, uint16 y, uint16 steps, uint8 meta, then int8 dx, dy per step."""

    steps = np.diff(xy, axis=0)
    if np.abs(steps).max(initial=0) > 127:
        raise SystemExit("polyline step beyond int8; lower PER_DEG")
    return struct.pack("<HHHB", int(xy[0, 0]), int(xy[0, 1]), len(steps), meta) + steps.astype(np.int8).tobytes()


def pack_levels(series: np.ndarray) -> bytes:
    """One series of levels as runs: the first level, then one byte per run.

    A run byte holds the run length minus one (6 bits, up to 64 days) and what follows
    it (2 bits): 0 the level rises by one, 1 it falls by one, 2 it becomes the next
    byte, 3 it stays (a longer run continues). The last run ends the series.
    """

    out = bytearray([int(series[0])])
    edges = np.flatnonzero(np.diff(series)) + 1
    starts = np.r_[0, edges]
    ends = np.r_[edges, len(series)]
    for k, (a, b) in enumerate(zip(starts, ends)):
        n = int(b - a)
        while n > 64:
            out.append(63 << 2 | 3)
            n -= 64
        if k == len(starts) - 1:
            out.append((n - 1) << 2 | 3)
            break
        step = int(series[b]) - int(series[a])
        out.append((n - 1) << 2 | {1: 0, -1: 1}.get(step, 2))
        if abs(step) != 1:
            out.append(int(series[b]))
    return bytes(out)


def lpt(sizes: dict[int, int], bins: int) -> dict[int, int]:
    """Whole basins to GPUs, largest first, each to the least loaded GPU."""

    load = [0] * bins
    owner = {}
    for basin, size in sorted(sizes.items(), key=lambda kv: (-kv[1], kv[0])):
        g = min(range(bins), key=lambda i: load[i])
        owner[basin] = g
        load[g] += size
    return owner


def read_params(path: str) -> dict:
    with netCDF4.Dataset(path) as ds:
        p = {k: np.asarray(ds.variables[v][:]) for k, v in (
            ("id", "catchment_id"), ("down", "downstream_id"), ("basin", "catchment_basin_id"),
            ("lon", "longitude"), ("lat", "latitude"), ("area", "upstream_area"),
            ("dist", "downstream_distance"), ("bank", "river_height"), ("width", "river_width"),
            ("length", "river_length"), ("carea", "catchment_area"), ("table", "flood_depth_table"),
            ("cx", "catchment_x"), ("cy", "catchment_y"),
        )}
    p["area"] = p["area"] / 1e6  # m2 -> km2
    index = {int(c): n for n, c in enumerate(p["id"])}
    p["d"] = np.array([index.get(int(c), n) for n, c in enumerate(p["down"])])  # self: river mouth
    p["xy"] = np.stack([np.rint((p["lon"] + 180) * PER_DEG), np.rint((90 - p["lat"]) * PER_DEG)], axis=1).astype(np.int64)
    return p


def read_daily(pattern: str, var: str, ids: np.ndarray) -> tuple[np.ndarray, int]:
    """Daily values (days, catchments) of one saved variable in parameter order, and the year."""

    out, year = None, None
    order = np.argsort(ids)
    for path in sorted(glob.glob(pattern)):
        with netCDF4.Dataset(path) as ds:
            t = ds.variables["time"]
            year = netCDF4.num2date(t[0], t.units, getattr(t, "calendar", "standard")).year
            cid = np.asarray(ds.variables["catchment_id"][:])
            pos = order[np.searchsorted(ids, cid, sorter=order)]
            data = np.asarray(ds.variables[var][:], dtype=np.float32)
        if out is None:
            out = np.full((data.shape[0], len(ids)), np.nan, np.float32)
        out[:, pos] = data
    if out is None:
        raise SystemExit(f"no output file matches {pattern}")
    return out, year


def reaches(p: dict, sel: np.ndarray, level: np.ndarray) -> list[list[int]]:
    """Chains of selected catchments; each ends where its downstream has another upstream or class."""

    d = p["d"]
    keep = np.zeros(len(d), bool)
    keep[sel] = True
    n_up = np.bincount(d[sel], minlength=len(d))
    up = np.full(len(d), -1)
    up[d[sel]] = sel  # the upstream catchment where n_up == 1

    def continues(m: int) -> bool:  # m extends the reach of its only upstream catchment
        return keep[m] and n_up[m] == 1 and level[m] == level[up[m]]

    chains = []
    for n in sel:
        if continues(n):
            continue
        chain = [int(n)]
        while continues(d[chain[-1]]):
            chain.append(int(d[chain[-1]]))
        chains.append(chain)
    return chains


def main_stem(p: dict, ups: dict[int, list[int]], lon: float, lat: float) -> list[int]:
    """Catchments from the source down to the largest catchment within 1 degree of (lon, lat)."""

    dist = ((p["lon"] - lon) * np.cos(np.radians(lat))) ** 2 + (p["lat"] - lat) ** 2
    near = np.where(dist < 1.0)[0]
    path = [int(near[np.argmax(p["area"][near])]) if near.size else int(np.argmin(dist))]
    while ups.get(path[-1]):
        path.append(max(ups[path[-1]], key=lambda m: p["area"][m]))
    return path[::-1]


def describe(mapname: str, year: int, forcing: str, spin_up: int) -> str:
    minutes = re.search(r"(\d+)min", mapname)
    grid = f"{int(minutes[1])}-arcmin global map ({mapname})" if minutes else mapname
    spun = f" after {spin_up} spin-up year{'s' if spin_up > 1 else ''}" if spin_up else " from a cold start"
    return f"Daily mean river discharge in {year}, simulated by CaMa-Flood-GPU on the {grid}, driven by {forcing}{spun}"


def runoff_map(path: Path) -> dict:
    """Annual mean runoff of a daily forcing file (time, lat, lon) in RUNOFF_DEG cells."""

    with netCDF4.Dataset(path) as ds:
        var = next(v for v in ds.variables.values() if v.ndim == 3)
        lat = np.asarray(ds.variables["lat"][:])
        days = var.shape[0]
        mean = np.zeros(var.shape[1:])
        count = np.zeros(var.shape[1:])
        for t in range(days):
            day = np.ma.filled(var[t].astype(float), np.nan)
            mean += np.nan_to_num(day)
            count += np.isfinite(day)
    step = abs(float(lat[1] - lat[0]))
    f = int(round(RUNOFF_DEG / step))
    if lat[0] < lat[-1]:
        mean, count = mean[::-1], count[::-1]
    ny, nx = mean.shape[0] // f, mean.shape[1] // f
    block = lambda a: a[: ny * f, : nx * f].reshape(ny, f, nx, f).sum(axis=(1, 3))  # noqa: E731
    land = block(count > 0)
    mm = np.where(land >= 0.3 * f * f, block(mean) / np.maximum(block(count), 1), np.nan)
    levels = np.where(np.isfinite(mm), 1 + np.rint(14 * np.sqrt(np.clip(mm, 0, RUNOFF_MAX) / RUNOFF_MAX)), 0).astype(np.uint8)
    north = float(max(lat[0], lat[-1]) + step / 2)
    print(f"runoff map: {nx} x {ny} cells of {RUNOFF_DEG} degrees, {int(np.isfinite(mm).sum())} on land, {days} days")
    return {"deg": RUNOFF_DEG, "west": -180, "north": round(north, 3), "nx": nx, "ny": ny, "max_mm": RUNOFF_MAX,
            "levels": b64(b"".join(pack_levels(row) for row in levels))}


def log_levels(q: np.ndarray, lo: float, hi: float) -> np.ndarray:
    """Discharge on the log scale [lo, hi] (log10 m3/s) in LEVELS steps; 0 for no flow."""

    with np.errstate(divide="ignore", invalid="ignore"):
        u = np.where(np.isfinite(q) & (q > 0), (np.log10(q) - lo) / (hi - lo), 0.0)
    return np.rint(u.clip(0, 1) * LEVELS).astype(np.uint8)


def range_levels(q: np.ndarray, steps: int) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Each row of discharge between its own lowest and highest value (log10), in `steps` steps."""

    lq = np.log10(np.clip(np.nan_to_num(q), 1e-3, None))
    lo, hi = lq.min(axis=1, keepdims=True), lq.max(axis=1, keepdims=True)
    return np.rint((lq - lo) / np.maximum(hi - lo, 1e-6) * steps).astype(np.uint8), lo[:, 0], hi[:, 0]


def plan_view(p: dict, k: int, hires: Path, daily: np.ndarray) -> dict:
    """Unit catchments (1-arcmin pixels) and rivers around catchment k and its downstream,
    with the daily discharge of each catchment between its own lowest and highest of the
    year on a log scale, which colours its rivers."""

    shape = (180 * HIRES, 360 * HIRES)
    cat = np.memmap(hires / "1min.catmxy.bin", dtype="<i2", mode="r", shape=(2, *shape))
    up = np.memmap(hires / "1min.uparea.bin", dtype="<f4", mode="r", shape=shape)
    down = np.memmap(hires / "1min.downxy.bin", dtype="<i2", mode="r", shape=(2, *shape))
    d = int(p["d"][k])
    lon = (p["lon"][k] + p["lon"][d]) / 2
    lat = (p["lat"][k] + p["lat"][d]) / 2
    c0 = int((lon - PLAN_HALF[0] + 180) * HIRES)
    r0 = int((90 - lat - PLAN_HALF[1]) * HIRES)
    ny, nx = int(2 * PLAN_HALF[1] * HIRES), int(2 * PLAN_HALF[0] * HIRES)
    win = (slice(r0, r0 + ny), slice(c0, c0 + nx))
    index = {(int(x), int(y)): n for n, (x, y) in enumerate(zip(p["cx"], p["cy"]))}
    gx, gy = np.asarray(cat[0][win]) - 1, np.asarray(cat[1][win]) - 1
    owner = np.array([index.get((int(x), int(y)), -1) for x, y in zip(gx.ravel(), gy.ravel())])
    found = [int(n) for n in np.unique(owner) if n >= 0]
    if len(found) > 254:
        raise SystemExit("too many catchments in the plan view")
    local = {n: i + 1 for i, n in enumerate(found)}
    ids = np.array([local.get(int(n), 0) for n in owner], dtype=np.uint8)
    runs = bytearray()
    start = 0
    for i in range(1, ids.size + 1):
        if i == ids.size or ids[i] != ids[start] or i - start == 255:
            runs += bytes([ids[start], i - start])
            start = i
    # rivers: chains of pixels down the 1-arcmin flow directions, split by upstream-area class
    area = np.asarray(up[win])
    dx, dy = np.asarray(down[0][win]), np.asarray(down[1][win])
    cls = np.searchsorted(RIVER_KM2, area, side="right") - 1
    river = cls >= 0
    has_up = np.zeros_like(river)
    for r, c in zip(*np.nonzero(river)):
        rr, cc = r + dy[r, c], c + dx[r, c]
        if 0 <= rr < ny and 0 <= cc < nx and river[rr, cc]:
            has_up[rr, cc] = True
    seen = np.zeros_like(river)
    grid = ids.reshape(ny, nx)
    lines, owners = bytearray(), []

    def emit(pts: list) -> None:  # a chain in one catchment and one class
        nonlocal lines
        lines += polyline(np.array([(c0 + q[1], r0 + q[0]) for q in pts]), int(cls[pts[0]]))
        owners.append(int(grid[pts[0]]))

    for r, c in zip(*np.nonzero(river & ~has_up)):
        pts = [(r, c)]
        while True:
            r1, c1 = pts[-1]
            rr, cc = r1 + dy[r1, c1], c1 + dx[r1, c1]
            if not (0 <= rr < ny and 0 <= cc < nx) or not river[rr, cc] or seen[r1, c1]:
                break
            seen[r1, c1] = True
            pts.append((rr, cc))
            if cls[rr, cc] != cls[pts[0]] or grid[rr, cc] != grid[pts[0]] or seen[rr, cc]:
                emit(pts)
                pts = [(rr, cc)]
        if len(pts) > 1:
            emit(pts)
    print(f"plan view: {nx} x {ny} pixels, {len(found)} catchments, {len(runs) // 2} runs, {len(lines)} bytes of rivers")
    return {
        "west": c0 / HIRES - 180, "north": 90 - r0 / HIRES, "per_deg": HIRES, "nx": nx, "ny": ny,
        "ids": b64(bytes(runs)), "rivers": b64(bytes(lines)), "river_ids": owners,
        "q": b64(b"".join(pack_levels(s) for s in range_levels(daily[:, found].T, LEVELS)[0])),
        "station": local[k], "down": local[d],
        "outlets": [[round(float(p["lon"][n]), 3), round(float(p["lat"][n]), 3)] for n in (k, d)],
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--params", required=True, help="parameters.nc of the run")
    ap.add_argument("--run", required=True, type=Path, help="output directory of the run")
    ap.add_argument("--runoff", required=True, type=Path, help="the runoff forcing file of the simulated year")
    ap.add_argument("--hires", required=True, type=Path, help="directory of the 1-arcmin maps")
    ap.add_argument("--forcing", required=True, help="the runoff forcing, as it reads in the caption")
    ap.add_argument("--spin-up-years", required=True, type=int, help="spin-up cycles before the saved year")
    ap.add_argument("--gpus", type=int, default=4)
    ap.add_argument("--min-upstream-km2", type=float, default=20000.0)
    a = ap.parse_args()

    p = read_params(a.params)
    daily, year = read_daily(str(a.run / "total_outflow_mean_rank*.nc"), "total_outflow_mean", p["id"])
    mapname = Path(a.params).parent.name

    basins, sizes = np.unique(p["basin"], return_counts=True)
    owner = lpt({int(b): int(s) for b, s in zip(basins, sizes)}, a.gpus)
    counts = [0] * a.gpus
    for b, s in zip(basins, sizes):
        counts[owner[int(b)]] += int(s)

    n_all = np.arange(len(p["d"]))
    sel = n_all[(p["area"] >= a.min_upstream_km2) & (p["d"] != n_all)]
    sel = sel[np.abs(p["lon"][p["d"][sel]] - p["lon"][sel]) <= 90]  # not across the dateline
    level = np.maximum(np.searchsorted(LEVEL_KM2, p["area"], side="right") - 1, 0)
    chains = reaches(p, sel, level)

    net = bytearray()
    for chain in chains:
        xy = p["xy"][chain + [int(p["d"][chain[-1]])]]
        net += polyline(xy, owner[int(p["basin"][chain[0]])] * 8 + int(level[chain[-1]]))
    q = daily[:, [c[-1] for c in chains]].T  # (reaches, days), at each reach's end
    pos = q[np.isfinite(q) & (q > 0)]
    hi = float(np.ceil(np.log10(pos.max())))
    lo = max(float(np.floor(np.log10(pos.min()))), hi - DECADES)
    levels = log_levels(q, lo, hi)
    fine = np.flatnonzero(level[[c[-1] for c in chains]] >= FINE_LEVEL)
    fine_levels, fine_lo, fine_hi = range_levels(q[fine], FINE_STEPS)
    mouths = np.nansum(daily[:, p["d"] == n_all], axis=1)

    ups: dict[int, list[int]] = {}
    for n, d in enumerate(p["d"]):
        if d != n:
            ups.setdefault(int(d), []).append(n)
    stems = [(name, main_stem(p, ups, lon, lat)) for name, lon, lat in MAIN_STEMS]
    for name, path in stems:
        print(f"{name:12s} mouth {p['lon'][path[-1]]:8.2f} {p['lat'][path[-1]]:7.2f}  {p['area'][path[-1]]:10.0f} km2  {len(path)} catchments")

    write_js("rivers", {
        "caption": describe(mapname, year, a.forcing, a.spin_up_years),
        "year": year,
        "per_deg": PER_DEG,
        "net": b64(bytes(net)),
        "days": int(q.shape[1]),
        "q": b64(b"".join(pack_levels(s) for s in levels)),
        "fine": {
            "reaches": fine.tolist(), "steps": FINE_STEPS,
            "lo": np.round(fine_lo, 3).tolist(), "hi": np.round(fine_hi, 3).tolist(),
            "q": b64(b"".join(pack_levels(s) for s in fine_levels)),
        },
        "qlog": [lo, hi],
        "spark": np.rint(100 * mouths / mouths.max()).astype(int).tolist(),
        "gpus": counts,
        "stems": [{"name": name, "path": b64(polyline(p["xy"][path]))} for name, path in stems],
        "runoff": runoff_map(a.runoff),
    })

    depth = read_daily(str(a.run / "river_depth_mean_rank*.nc"), "river_depth_mean", p["id"])[0]
    monthly = read_daily(str(a.run / "total_outflow_max_mean_rank*.nc"), "total_outflow_max_mean", p["id"])[0]
    stations = []
    for river, gauge, lon, lat in STATIONS:
        path = dict(stems)[river]
        k = path[int(np.argmin((p["lon"][path] - lon) ** 2 + (p["lat"][path] - lat) ** 2))]
        print(f"{river} at {gauge}: catchment at {p['lon'][k]:.2f} {p['lat'][k]:.2f}")
        stations.append({
            "name": f"{river} at {gauge}",
            "distance_m": round(float(p["dist"][k])),
            "bank_m": round(float(p["bank"][k]), 2),
            "width_m": round(float(p["width"][k])),
            "length_m": round(float(p["length"][k])),
            "area_km2": round(float(p["carea"][k]) / 1e6, 1),
            "flood_table_m": [round(float(v), 2) for v in p["table"][k]],
            "outflow": [None if not np.isfinite(v) else round(float(v)) for v in daily[:, k]],
            "depth": [None if not np.isfinite(v) else round(float(v), 2) for v in depth[:, k]],
            "monthly_max": [None if not np.isfinite(v) else round(float(v)) for v in monthly[:, k]],
        })
    write_js("hydrograph", {"year": year, "stations": stations, "plan": plan_view(p, k, a.hires, daily)})

if __name__ == "__main__":
    main()
